// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPLxs8_jcgsgrQcceljXNH3yphzRCUZeI',
    appId: '1:93746298794:web:de3df4eec767655c5035d3',
    messagingSenderId: '93746298794',
    projectId: 'whatsapp-clone-backend-82080',
    authDomain: 'whatsapp-clone-backend-82080.firebaseapp.com',
    storageBucket: 'whatsapp-clone-backend-82080.appspot.com',
    measurementId: 'G-KVTEH8E6WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQksGIQPwsL8dk2v4o5_a5cdkN1B6-X2w',
    appId: '1:93746298794:android:974dd4380550af225035d3',
    messagingSenderId: '93746298794',
    projectId: 'whatsapp-clone-backend-82080',
    storageBucket: 'whatsapp-clone-backend-82080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBattFVwPVfNqCv4zfcrK1TvsRZcSsNlq0',
    appId: '1:93746298794:ios:15262b6aa4f882055035d3',
    messagingSenderId: '93746298794',
    projectId: 'whatsapp-clone-backend-82080',
    storageBucket: 'whatsapp-clone-backend-82080.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
